# Generated by Django 5.2.3 on 2026-02-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrolink', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('buyer', 'Buyer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
